import sys

# Chop the first few lines of the file, one is blank and one indicates the autogenerated nature of the file
linesToIgnore = 2

# Items in a content line that should be replaced
replacements = {
	"[img=music]": '♫'
}
mediaTypes = [
	"CDs",
	"VHS",
	"Home-VHS",
	"Retail-VHS"
]
valueNames = [
	('title', True),
	('extra', True),
	('author', True),
	('subtitle', True),
	('itemDisplayName', True),
	('spawning', False),
	('category', False)
]

import json
from types import SimpleNamespace

templateFiles = {}
RecMedia = {}
TranslationData = {}
TranslationData[None] = None

def init():	
	global RecMedia

	readTranslationData()
	readTemplateFiles()
	RecMedia = readLuaData("intermediate.out")
	

def readTemplateFiles():
	global templateFiles

	# Try to open all of our wikiformat files, if they don't exist, throw an error
	try: 
		for type in mediaTypes:
			f = open('Templates/' + type.replace(' ', '_') + '.wikiformat')
			templateFiles[type] = f.read()
			f.close()
		f = open('Templates/contentLine.wikiformat')
		templateFiles['contentLine'] = f.read()
		f.close()
		
	except:
		print("Missing template file. Ensure that a file exists under Templates for each of the following items:", 
			[x.replace(' ', '_') + '.wikiformat' for x in mediaTypes],
			"and 'contentLine.wikiformat'"
		)

def readLuaData(filepath):
	f = open(filepath)
	data = f.read()
	out = json.loads(data, object_hook=lambda d: SimpleNamespace(**d))
	f.close()
	return out

def readTranslationData():
	global TranslationData
	translationDataPath = sys.argv[1] + "/media/lua/shared/Translate/EN/Recorded_Media_EN.txt"

	f = open(translationDataPath)
	lines = f.readlines()
	lines = lines[linesToIgnore:]
	f.close()
	
	for line in lines:
		for toReplace, replacement in replacements.items():
			line = line.replace(toReplace, replacement)
			
		lineSplit = line.split("=")
		key = lineSplit[0].strip()
		value = "=".join(lineSplit[1:])
		TranslationData[key] = value

def writeOutput():
	global RecMedia
	global TranslationData
	
	for key, value in vars(RecMedia).items():
		template = templateFiles[value.category]
		contentLineTemplate = templateFiles['contentLine']
		
		id = key
		foundValues = {}
		
		for valueName, findTranslation in valueNames:
			if findTranslation:
				found = TranslationData[getattr(value, valueName, None)]
				if found is not None:
					found = found.strip().strip('"')
					
				foundValues[valueName] = found
			else:
				foundValues[valueName] = getattr(value, valueName, None)
		
		
		lineStrings = []
		for line in value.lines:
			r = line.r
			g = line.g
			b = line.b
			codes = line.codes
			text = TranslationData[line.text].strip()[1:-1]
			
			newLine = contentLineTemplate
			newLine = replaceOrAppendDelete(newLine, "%r%", r)
			newLine = replaceOrAppendDelete(newLine, "%g%", g)
			newLine = replaceOrAppendDelete(newLine, "%b%", b)
			newLine = replaceOrAppendDelete(newLine, "%codes%", codes)
			newLine = replaceOrAppendDelete(newLine, "%mediaContentItem%", text)
			
			if not "||DELETE||" in newLine:
				lineStrings.append(newLine)
			
		mediaContent = "\n".join(lineStrings)
		
		outputLines = []
		templateLines = template.split("\n")
		for line in templateLines:
			for k, v in foundValues.items():
				line = replaceOrAppendDelete(line, '%'+k+'%', v)
				
			if not "||DELETE||" in line:
				outputLines.append(line)
				
		output = "\n".join(outputLines)
		output = output.replace("%mediaContent%", mediaContent)
		output = output.replace("%id%", str(id))
		
		filename = foundValues['itemDisplayName'] if not foundValues['itemDisplayName'] == None else id
		fileName = filename.strip().strip('"').replace('.', '').replace(' ', '_').replace('?', '').replace('/', '-').replace(':', '')
		
		print("Writing file:","Output/" + fileName + ".wikioutput")
		f = open("Output/" + fileName + ".wikioutput", 'w', encoding="utf-8")
		f.write(output)
		f.close()

def replaceOrAppendDelete(line, valToReplace, replacement):
	if (replacement == None) and ("%if%" in line):
		return line + "||DELETE||"
	
	if replacement == None:
		replacement = '[[ VALUE NOT PRESENT ]]'
	
	replacements = line.count(valToReplace)
	if replacements > 0:
		line = line.replace(valToReplace, str(replacement)).replace("%if%", "", replacements)
	
	return line

init()
writeOutput()